# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
  - r: release
    after_success: Rscript -e 'covr::codecov()'

  - r: devel
  - r: oldrel
  - r: 3.6
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
