# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
r_packages:
  - covr

matrix:
  include:
  - r: release
    after_success:
      - Rscript -e 'covr::codecov(token = "9c67741e-cd05-462b-b937-5dc67f0e6721")'
      - Rscript -e 'library(covr); codecov(token = "9c67741e-cd05-462b-b937-5dc67f0e6721")'

  - r: devel
  - r: 3.6
  - r: 3.5
